// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"fi_FI": &dictionary{index: fi_FIIndex, data: fi_FIData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Disable color output":                          7,
	"Examples:":                                     11,
	"Full year:":                                    12,
	"How many months per line":                      2,
	"How many next months":                          0,
	"How many previous months":                      1,
	"Month 1-12 (defaults to current month)":        4,
	"One calendar at a time:":                       14,
	"Only one month, equivalent to -next 0 -prev 0": 6,
	"Only this month:":                              13,
	"Parameters:":                                   9,
	"Print full year":                               5,
	"Start day for week 0-6 (sun-sat)":              8,
	"Year (defaults to current year)":               3,
	"april":                                         25,
	"august":                                        29,
	"december":                                      33,
	"default: %q":                                   10,
	"february":                                      23,
	"january":                                       22,
	"july":                                          28,
	"june":                                          27,
	"march":                                         24,
	"may":                                           26,
	"november":                                      32,
	"october":                                       31,
	"september":                                     30,
	"short.friday":                                  19,
	"short.monday":                                  15,
	"short.saturday":                                20,
	"short.sunday":                                  21,
	"short.thursday":                                18,
	"short.tuesday":                                 16,
	"short.wednesday":                               17,
	"week":                                          34,
}

var en_USIndex = []uint32{ // 36 elements
	// Entry 0 - 1F
	0x00000000, 0x00000015, 0x0000002e, 0x00000047,
	0x00000067, 0x0000008e, 0x0000009e, 0x000000cc,
	0x000000e1, 0x00000102, 0x0000010e, 0x0000011d,
	0x00000127, 0x00000132, 0x00000143, 0x0000015b,
	0x0000015e, 0x00000161, 0x00000164, 0x00000167,
	0x0000016a, 0x0000016d, 0x00000170, 0x00000178,
	0x00000181, 0x00000187, 0x0000018d, 0x00000191,
	0x00000196, 0x0000019b, 0x000001a2, 0x000001ac,
	// Entry 20 - 3F
	0x000001b4, 0x000001bd, 0x000001c6, 0x000001ca,
} // Size: 168 bytes

const en_USData string = "" + // Size: 458 bytes
	"\x02How many next months\x02How many previous months\x02How many months " +
	"per line\x02Year (defaults to current year)\x02Month 1-12 (defaults to c" +
	"urrent month)\x02Print full year\x02Only one month, equivalent to -next " +
	"0 -prev 0\x02Disable color output\x02Start day for week 0-6 (sun-sat)" +
	"\x02Parameters:\x02default: %[1]q\x02Examples:\x02Full year:\x02Only thi" +
	"s month:\x02One calendar at a time:\x02ma\x02ti\x02ke\x02to\x02pe\x02la" +
	"\x02su\x02january\x02february\x02march\x02april\x02may\x02june\x02july" +
	"\x02august\x02september\x02october\x02november\x02december\x02vko"

var fi_FIIndex = []uint32{ // 36 elements
	// Entry 0 - 1F
	0x00000000, 0x00000021, 0x00000043, 0x00000063,
	0x00000080, 0x000000a8, 0x000000bb, 0x000000f3,
	0x0000010a, 0x00000131, 0x0000013d, 0x0000014a,
	0x00000158, 0x00000164, 0x0000017a, 0x00000195,
	0x00000198, 0x0000019b, 0x0000019e, 0x000001a1,
	0x000001a4, 0x000001a7, 0x000001aa, 0x000001b3,
	0x000001bc, 0x000001c6, 0x000001cf, 0x000001d8,
	0x000001e1, 0x000001eb, 0x000001f2, 0x000001fa,
	// Entry 20 - 3F
	0x00000202, 0x0000020c, 0x00000215, 0x00000219,
} // Size: 168 bytes

const fi_FIData string = "" + // Size: 537 bytes
	"\x02Kuinka monta seuraavaa kuukautta\x02Kuinka monta edellistä kuukautta" +
	"\x02Kuinka monta kuukautta per rivi\x02Vuosi (vakiona kuluva vuosi)\x02K" +
	"uukausi 1-12 (vakiona kuluva kuukausi)\x02Tulosta koko vuosi\x02Vain yks" +
	"i kuukausi, vastaa parametrejä -next 0 -prev 0\x02Älä tulosta värejä\x02" +
	"Ensimmäinen viikonpäivä 0-6 (su-la)\x02Parametrit:\x02vakio: %[1]q\x02Es" +
	"imerkkejä:\x02Koko vuosi:\x02Vain tämä kuukausi:\x02Yksi kalenteri kerra" +
	"llaan:\x02ma\x02ti\x02ke\x02to\x02pe\x02la\x02su\x02tammikuu\x02helmikuu" +
	"\x02maaliskuu\x02huhtikuu\x02toukokuu\x02kesäkuu\x02heinäkuu\x02elokuu" +
	"\x02syyskuu\x02lokakuu\x02marraskuu\x02joulukuu\x02vko"

	// Total table size 1331 bytes (1KiB); checksum: 6C32E6F1
